[project]
name = "python-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.2.14",
    "numba>=0.65.0",
    "scipy>=1.17.1",
    "torch>=2.11.0",
    "transformers>=5.4.0",
]

[tool.uv.sources]
torch = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
